name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh_command:
    name: Deploy website
    # needs: terraform_apply
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run command on remote server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          private_key_filename: id_ed25519
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
#          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
#          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
          commands: |
            cd ${{ secrets.PROJECT_ROOT }}
            chmod +x ./redeploy-site.sh
            ./redeploy-site.sh
