name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install
      - run: npm install
      - run: npm run build
      - run: cp .env.example .env
      - run: php artisan key:generate --ansi
      - run: php artisan test --parallel
  ssh_command:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Connect and run command on remote server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          private_key_filename: id_ed25519
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          commands: |
            cd ${{ secrets.PROJECT_ROOT }}
            git fetch && git reset origin/main --hard
            chmod -R 755 storage bootstrap/cache
            chmod +x ./redeploy-site.sh
            ./redeploy-site.sh
